services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_USE_MOCK: "true"
        NEXT_PUBLIC_API_URL: "http://localhost:3000"
    environment:
      NEXT_PUBLIC_USE_MOCK: true
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
      NODE_ENV: development
    ports:
      - 3000:3000
