import { MockFeedService } from '@/services/mocks/feedService';
import {
  flushMockLocalStorage,
  getMockUsersStore,
} from '@/services/mocks/mockSystemStore';

describe('MockFeedService', () => {
  let service: MockFeedService;

  beforeEach(() => {
    jest.clearAllMocks();
    flushMockLocalStorage();
    service = new MockFeedService();
  });

  it('returns feed items generated by followed users', async () => {
    const users = getMockUsersStore();
    const me = users.find((user) => user.id === 1);
    if (!me) throw new Error('seed user 1 not found');

    me.following.add(7);
    me.blocked.delete(7);

    const feed = await service.getfeed({ page: 0, size: 20 });

    expect(feed.content?.length).toBeGreaterThan(0);

    const followedUsers = users.filter((user) => me.following.has(user.id));
    const followedUserIds = new Set(followedUsers.map((user) => user.id));
    const followedUsernames = new Set(
      followedUsers.map((user) => user.username.toLowerCase())
    );

    const allFromFollowed = (feed.content ?? []).every((item) => {
      if (item.type === 'TRACK_LIKED' || item.type === 'PLAYLIST_LIKED') {
        return true;
      }

      const resource = item.resource;
      if (resource.track) {
        const artistId = resource.track.artist.id;
        const artistUsername = resource.track.artist.username.toLowerCase();
        return (
          followedUserIds.has(artistId) ||
          followedUsernames.has(artistUsername)
        );
      }

      if (resource.playlist) {
        const ownerId = resource.playlist.owner.id;
        const ownerUsername = resource.playlist.owner.username.toLowerCase();
        return (
          followedUserIds.has(ownerId) ||
          followedUsernames.has(ownerUsername)
        );
      }

      if (item.repostedBy) {
        return followedUserIds.has(item.repostedBy.id);
      }

      return false;
    });

    expect(allFromFollowed).toBe(true);
  });

  it('excludes blocked users content even if they are followed', async () => {
    const users = getMockUsersStore();
    const me = users.find((user) => user.id === 1);
    if (!me) throw new Error('seed user 1 not found');

    me.following.add(7);
    me.blocked.add(7);

    const feed = await service.getfeed({ page: 0, size: 20 });

    const hasBlockedContent = (feed.content ?? []).some((item) => {
      if (item.resource.track) {
        return (
          item.resource.track.artist.id === 7 ||
          item.resource.track.artist.username === 'mockartist'
        );
      }
      if (item.resource.playlist) {
        return (
          item.resource.playlist.owner.id === 7 ||
          item.resource.playlist.owner.username === 'mockartist'
        );
      }
      if (item.repostedBy) {
        return item.repostedBy.id === 7;
      }
      return false;
    });

    expect(hasBlockedContent).toBe(false);
  });

  it('returns paginated feed metadata', async () => {
    const users = getMockUsersStore();
    const me = users.find((user) => user.id === 1);
    if (!me) throw new Error('seed user 1 not found');

    me.following.add(7);
    me.blocked.delete(7);

    const feed = await service.getfeed({ page: 0, size: 1 });

    expect(feed.pageNumber).toBe(0);
    expect(feed.pageSize).toBe(1);
    expect(feed.totalElements).toBeGreaterThanOrEqual(1);
    expect(feed.totalPages).toBeGreaterThanOrEqual(1);
    expect(feed.content).toHaveLength(1);
  });
});
